### ISSUE TITLE
ModuleNotFoundError: No module named 'medpy'

### ISSUE THREAD

**Issue by bushraphd** [YUCOCOCS/Swin-TransUper#3]
I have imported the code from github and while running the code

!python /kaggle/working/Swin-TransUper/train.py

got error as 

Traceback (most recent call last):
  File "/kaggle/working/Swin-TransUper/train.py", line 10, in <module>
    from trainer import trainer_synapse,trainer_ISIC,trainer_busi,trainer_mix
  File "/kaggle/working/Swin-TransUper/trainer.py", line 17, in <module>
    from utils import DiceLoss
  File "/kaggle/working/Swin-TransUper/utils.py", line 3, in <module>
    from medpy import metric
ModuleNotFoundError: No module named 'medpy'

**Comment by YUCOCOCS** [comment]
This error shows that your conda environment is missing the medpy package. You can use the conda/pip install medpy command in your environment to install it.  I hope my answer can help you.

**Comment by bushraphd** [comment]
While running train.py I got error as 

Traceback (most recent call last):
  File "/kaggle/working/Swin-TransUper/train.py", line 10, in <module>
    from trainer import trainer_synapse,trainer_ISIC,trainer_busi,trainer_mix
  File "/kaggle/working/Swin-TransUper/trainer.py", line 20, in <module>
    from datasets.dataset_isic import isic_loader
ModuleNotFoundError: No module named 'datasets.dataset_isic'


Then I tried to install , !pip install datasets.dataset_isic I am getting error as 
ERROR: Could not find a version that satisfies the requirement datasets.dataset_isic (from versions: none)
ERROR: No matching distribution found for datasets.dataset_isic

My python version is Python 3.10.13
